### ISSUE TITLE
[我的订单]住后整理和住前打理无法取消订单，管理员账号无法对状态更新

### ISSUE THREAD

**Issue by lewiyue** [chaishen10000/51gj#10]
当生成一个住后整理和住前打理订单后，再弹出的订单中可以立刻取消。
如果不取消，再次进入我的订单中，查看对应的订单时，取消按钮无法显示和工作。
见下截图：
![default](https://cloud.githubusercontent.com/assets/10934139/18414964/4a01dd00-7812-11e6-9884-928eb0e5a7cb.png)

**Comment by lewiyue** [comment]
这个问题需要优先解决，导致基本的功能无法使用。

**Comment by chaishen10000** [comment]
已解决！

**Comment by lewiyue** [comment]
Assigned to me , and checked this issue.  Passed.
