### ISSUE TITLE
[物业现状]物业现状图库显示不出来

### ISSUE THREAD

**Issue by lewiyue** [chaishen10000/51gj#13]
在管理员微信端进入物业登记后，有现状图库按钮，点击进入后，可以上传图库。

问题1： 选择 其他类型上传图库后，图片显示的类别是“”家具现状登记“”，应该描述为“”其他类型登记“”

问题2： 上传图片时，有时间显示不出来图片。如下截图：
![default](https://cloud.githubusercontent.com/assets/10934139/18415664/d8460216-782c-11e6-9429-563ca8d775be.jpg)

**Comment by chaishen10000** [comment]
已修正

**Comment by lewiyue** [comment]
Assigned to me, and checked again. Passed.
